### ISSUE TITLE
강의실이 너무 덥다. 어떻게 하면 좋을 까요?

### ISSUE THREAD

**Issue by yong076** [GDGincheonAndroidStudy/Overview_GDGIncheon_Study#2]
강의실이 너무 더운데 스터디룸 대여는 어떻게 생각 하시나요?

**Comment by yong076** [comment]
저도 너무 더워요 옮겼으면 좋겠어요

**Comment by stomx** [comment]
인천에는 토즈같은곳없나요?

**Comment by bingwer** [comment]
토즈가 있긴한데 수용인원이 4~5명밖에 되지 않네요..

**Comment by yong076** [comment]
회의실 같인곳이면 좋을거 같은데. 저희회사 (홍대) 까지는 너무 멀겠죠? [하하하핫..]

**Comment by woosuk-oh** [comment]
거리 상관없다면 강남에 몇개 있는걸로 알고있습니다

**Comment by stomx** [comment]
스터디하기는 강남이 좋기는 한데....부평에서 출발해도 편도 1시간 30분이라....
신도림도 알아봤는데 있긴 있으나 최대 6명 정도인거 같아요...ㅠㅠ

**Comment by skeksksk** [comment]
저는 홍대쪽이 더빠르고 편한...

**Comment by cionman** [comment]
부천시청역 앞에 토즈가 생겼..

**Comment by cionman** [comment]
자리가 모자른...
