### ISSUE TITLE
깃허브 푸쉬 에러

### ISSUE THREAD

**Issue by bingwer** [GDGincheonAndroidStudy/Overview_GDGIncheon_Study#3]
![image](https://cloud.githubusercontent.com/assets/13097396/9160195/fb3221a6-3f70-11e5-8b11-3185f11d4411.png)

깃허브에 푸쉬하려고하는데 푸쉬가 거절되었다고 하고 로그를 보면 저렇게 나옵니다 어떻게 해결해야할까요?

**Comment by yong076** [comment]
1. commit만 한뒤에 Pull 한번 해보세요.
2. http://mobicon.tistory.com/162
- 보통 그런 경우 푸쉬 거절 이유는 현재 내 로컬 Repo에 있는 놈이 최신이 아니기 때문입니다. 혹은 .git 파일의 문제이기도 합니다 (이경우는 삽질이 ... ㄷㄷㄷ)
- 다른 곳에서 수정한것이 있다면 Pull 먼저 하고 난후 Push 하셔야 맞습니다.

**Comment by bingwer** [comment]
pull도 안되네요 ㅠㅠ 그냥 노트북꺼 옮겨서 했어요.. 커밋한게 다 날라가서 아쉽긴 하지만.. ㅜㅜ

**Comment by yong076** [comment]
으헝 [...] 화이팅.. .
