### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by bingwer** [GDGincheonAndroidStudy/Overview_GDGIncheon_Study#6]
제가 스터디 레포에 포크한 linux deploy라는 앱 요놈인데요
이거를 실행후 리눅스 deploy한 후에 하루 지나고 나니까
백그라운드에서 유지가 안되고 종료가 되어버렸네요
백그라운드에서 계속 실행이 유지되게하려면 어떻게 해야할까요?

**Comment by yong076** [comment]
실행된후에 종료가 된다는건 GC 때문에 삭제 되는 것인지. 어떤 문제 때문에 Crash 가 난것인지를 확인 해야 합니다.

그뒤에 몇가지의 예외처리로 감싸서 구현 하시면 됩니다.

**Comment by yong076** [comment]
P.S 또한 서비스의 서비스를 구현 해서 해당 서비스가 돌지 않을 경우에 서비스를 재 실행 시키는 루틴을 만드셔도됩니다.

Another Solution
1. 서비스에서 자신이 크래쉬가 되었다는것을 이벤트로 체크한 뒤에 다시 살리는 방법도 있습니다.

2.해당 크래쉬의 이유를 알고 고치는게 더 좋겠죠?
